[extract_tables]
prompt = """Extract tables from the image. Express the tables in Markdown.
Becareful with the layout of the tables, sometimes they are very complex.

do NOT reformat the tables. Extract tables with exactly the same layout from the image as much as possible.
make sure to draw border lines.
"""

[extract_coordinate]
prompt = """Extract a coordinate of the main figure from the image.
Here, 'figure' means drawings with caption starting with 'Fig.' or 'Figure.'

When extracting the bounding box, make sure to meet the following criteria:
- other than figure (i.e. table) shouldn't be included.
- The coordinate should not include other than figure.
- The coordinate should not stretch to left and right. 
- THe corrdinate should capture exact area of the figure.
- The coordinate should not include the caption of the figure.
- The coordinate should be represented as (x_min, y_min, x_max, y_max) of floating point numbers between 0 and 1.
- If the figure is not found, return (0, 0, 0, 0).

Return coordinate only if all of the criteria are met.
Otherwise, return (0, 0, 0, 0).
"""

[describe_figure]
prompt = """based on the paper, give me the following information about the attached $type
- actual caption of the $type from the paper with the $type number.
- if the actual caption is short, provide longer description for better understanding.
- if the actual caption is long enough, provide short description for better readability.
- specify the section title of the paper that the $type belongs to.
"""

[describe_figure_from_html]
prompt = """Below is the caption of the $type from the paper.
caption: $caption

based on the attached paper, give me the following information about the $type.
- if the actual caption is short, provide longer description for better understanding.
- if the actual caption is long enough, provide short description for better readability.
- specify the section title of the paper that the $type belongs to.
"""

[reformat_table]
prompt = """Reformat the below HTML table into Markdown table.
Also, if images are contained in the table, convert the image path as https://arxiv.org/html/arxiv_id/filename.png
The current arxiv_id is $arxiv_id.

$html_table
"""

[double_check_figure]
prompt = """The provided figure of image was parsed from the paper by AI.

That AI could have made a mistake, so make sure to meet the following criteria:
- It should contain visual information.
- It should be representative figure of the paper.
- If it contains text, it should be part of the visual information.
- Only text is not a valid image.

If one of the criterias is not met, say no.
Only if all criterias are met, say yes.
"""

[double_check_table]
prompt = """The below HTML table was parsed from the paper by the other AI.

That AI could have made a mistake, so check the HTML table carefully with the the following criteria:
-it should come from the paper
- it should be correctly parsed
- It should be a real table 
- it should contain insightful information
- it shouldt be pseudo-code
- it shouldn't be author information

Return True only all of the criteria are met.

Think carefully
--------------------------------
$table
"""

[extract_essentials]
prompt = """You are a highly skilled AI research assistant tasked with summarizing academic papers for researchers. Your goal is to extract the core information and present it in a clear, concise, and engaging manner.

For the given research paper, please provide the following:
1. Catchy Summary: Condense the paper's main contribution into a single, eye-catching sentence with less than 200 characters. This should be easily understandable and pique the reader's interest.
2. TL;DR:  Provide a comprehensive summary of the paper in 2 paragraphs. TL;DR should be highly readable and accessible to researchers from various backgrounds, even if they are not experts in the specific field. Focus on clarity and avoid technical jargon as much as possible. Explain key concepts, methods, and findings in a way that is easy to grasp. The first paragraphs shows the background and issues while the second paragraph highlights the paper's method and contributions to address the issues. Each paragraph should be written in 500 characters. 
3. Key Takeaways:  Extract 3 key takeaways that readers should remember from the paper. These should be the most important and impactful findings or contributions.
4. Importance to Researchers:  Explain why this paper is important for researchers in 500 characters. Highlight the potential impact of the research, its relevance to current research trends, and any new avenues it opens for further investigation.

Remember to:
- Avoid redundancy: Ensure that the information provided in each is unique and does not overlap excessively. (i.e. if you already mentioned the project name from the TL;DR, do not mention it again in the other sections)
- Focus on the main idea: Prioritize the core contributions and findings of the paper, ensuring that readers can grasp the main idea effectively.
- Maintain a professional and objective tone: Present the information in a neutral and unbiased manner.
- Use **bold** to highlight the important parts of the text in the sections "TL;DR" and "Importance to Researchers.
"""

[extract_affiliation]
prompt = """Extract a single affiliation of the main author from the paper.

Some of the known affiliations are listed below. 
If this paper's affiliation is not listed, suggest new affiliation with not too much length. 
Otherwise, return the exact affiliation name that the paper belongs to from the list below.
The affiliation name should not contain any definite article (i.e. "the", "a", "an").

known affiliations: $known_affiliations
"""

[extract_category]
prompt = """Extract a category and sub-category of the paper.

Some of the known categories and sub-categories are listed below.
If this paper's category and sub-category are not listed, suggest new ones with not too much length.
Otherwise, return the exact category and sub-category name that the paper belongs to from the list below.
The category and sub-category name should not contain any definite article (i.e. "the", "a", "an").

known categories: $known_categories
"""

[extract_sections]
prompt = """Given a PDF research paper as input, generate up to 5 insightful headings that capture key themes and points of depth, moving beyond simple takeaways. The goal is to extract brief titles (up to 15 characters each) that reflect deeper insights such as the paper's background, specific experimental methods, future research directions, and limitations. These titles should not necessarily match the paper's section titles verbatim but should be creatively crafted to highlight essential insights effectively.
"""

[extract_references]
prompt = """rom the citations in this paper, identify the top 5 most important reference papers. For each, provide the following information:
- The name of the first author.
- The title of the reference paper.
- Publication date of the reference paper in YYYY-MM-DD format.
- A one-sentence explanation detailing why this reference is considered among the most important.
"""

[extract_section_details]
prompt = """Given a PDF research paper as input, analyze and provide a summary about the heading titled as '$section_title'.
- The summary should be written with a thoughtful and in-depth approach to uncover valuable insights.
- The summary should be written in a single paragraph, and it should be 800 characters long.
- Use **bold** formatting to emphasize key points.
"""